account/urls.py
from django.urls import path
from .views import RegisterView, LoginView

app_name = 'account'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('login', LoginView.as_view(), name='login')
]

farmhive/urls.py
from django.urls import path
from .views import *

app_name = 'farm'

urlpatterns = [
    path('', home_view, name='home'),
    # path('about/', about_view, name='about'),
    path('gellary/', gellary_view, name='gellary'),
    path('digiFarms<int:department_id>', digiFarms_details, name='digifarm_details'),
    path('digiFarms/', digiFarms, name='digifarm'),
    path('gallery_gallery/', galleryDetail_view, name='gellery_detail'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('home/', home_view, name='home'),
    path('contact/', contact_view, name='contact'),
    path('news_list/', news_list, name='news_list'),
    path('news_list/<int:article_id>/', article_details, name='article_details'),
    path('projects/', project_list_view, name='project_list'),
    path('projects/<int:pk>/', project_details_view, name='project_detail'),
    path('search/', search_view, name='search'),
    path('team/', team_list_view, name='team'),
    path('team/<int:team_id>/', team_details_view, name='team_details'),
    path('service/', service_view, name='services'),
    path('about/', about_view, name='about'),
    path('gallery/', galleryView, name='gallery'),
    path('tech_hive/', techhiveView, name='techhive'),
    path('farm_hive/', farmhiveView, name='farmhive'),
    path('multimedia_hive/', multimediaView, name='multihive'),
    path('details/<str:item_type>/<int:pk>', buy_now, name='details'),
]

techfarm/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import home_view
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', home_view, name='home'),
    path("admin/", admin.site.urls),
    path('account/', include('account.urls')),
    path('main/', include('main.urls')),
    path('farmhive/', include('farmhive.urls')),
    path('techhive/', include('techhive.urls')),
    path('payment/', include('payment.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techhive/urls.py
from django.urls import path
from .views import *

app_name = 'techhive'

urlpatterns = [
    path('', techHiveHome_view, name='techhivehome'),
]

farmhive/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Home(models.Model):
    top_home_image = models.ImageField(upload_to='farm_hive_home_images')
    title_of_content = models.CharField(max_length=120, default='Tech Farm Hub')
    short_content = models.CharField(max_length=255, default='Tech Farm Hub')

    def __str__(self) -> str:
        return self.title_of_content


class Departments(models.Model):
    name = models.CharField(max_length=50, default='Farm Hive')
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.name}, {self.date_created}"

class SubDepartment(models.Model):
    departments = models.ForeignKey(Departments, on_delete=models.CASCADE)
    sub_department_name = models.CharField(max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
 
    def __str__(self) -> str:
        return self.sub_department_name


class DigitalFarms(models.Model):
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)
    department_name = models.CharField(max_length=150)
    title = models.CharField(max_length=255, default='Farm Hive')
    description = models.CharField(max_length=500)
    total_departments = models.IntegerField(default=0, blank=True)
    upload_video = models.FileField(upload_to='digifarms_images')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.created_at}, {self.department_name}"

@receiver(post_save, sender=DigitalFarms)
def increment_total_departments(sender, instance, created, **kwargs):
    if created:
        instance.total_departments = DigitalFarms.objects.count()
        instance.save()


    

class VideoGellary(models.Model):
    title = models.CharField(max_length=150, default='Farm Hive')
    video = models.FileField(upload_to='farm_hive_vedos')
    created_at = models.DateTimeField(auto_now_add=True)


class Pictures(models.Model):
    title = models.CharField(max_length=150)
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

techhive/models.py
from django.db import models
from decimal import Decimal

class TechHiveDeparments(models.Model):
    department_name = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.department_name
    
class Section(models.Model):
    department = models.ForeignKey(TechHiveDeparments, on_delete=models.CASCADE)
    section_name = models.CharField(max_length=100, blank=False, unique=True)
    short_description = models.CharField(max_length=100, blank=False, unique=True)
    full_description = models.CharField(max_length=1500, blank=True, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.section_name
    
class Payment(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=5)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Price for {self.section.section_name} = {self.price}"
    
class Discount(models.Model):
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE)
    discount = models.BooleanField(default=False)
    discount_percent = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def set_discount(self, amount):
        if self.discount:
            self.discount_percent = amount
            self.payment.price = self.payment.price - self.discount_percent
            self.payment.save()

class Promotions(models.Model):
    payment = models.OneToOneField(Payment, on_delete=models.CASCADE, related_name='promotion', null=True, blank=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    percentage = models.DecimalField(decimal_places=2, max_digits=5, default=0)

    def apply_promotion(self):
        if not self.payment.discount:
            self.payment.price = self.payment.price * (1 - self.percentage / 100)
            self.payment.save()

farmhive/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

active_app = 'farm'

def home_view(request):
    home_contents = Home.objects.all()
    pictures = Pictures.objects.all()[:3]
    videos = VideoGellary.objects.all()[:3]
    departments = Departments.objects.all()[:5]
    return render(request, 'farm/index.html', {'departments': departments, 'videos': videos,
                        'home_contents': home_contents, 'pictures': pictures,'active_app': active_app})

# def about_view(request):
#     about_farmhive = AboutFarmHive.objects.all()
#     return render(request, 'farm/about.html', {'about': about_farmhive, 'active_app': active_app})

def gellary_view(request):
    gellary = VideoGellary.objects.all()[:5]
    pictures = Pictures.objects.all()[:5]
    return render(request, 'farm/gellary.html', {'gellary': gellary, 'pictures': pictures, 'active_app': active_app})

def galleryDetail_view(request):
    gellary = VideoGellary.objects.all()
    pictures = Pictures.objects.all()

    return render(request, 'farm/detail_gallery.html', {'gellary': gellary, 'pictures': pictures, 'active_app': active_app})

def digiFarms(request):
    digitalfarms = DigitalFarms.objects.all()

    return render(request, 'farm/digifarms.html', {'digitalfarms': digitalfarms, 'active_app': active_app})

def digiFarms_details(request, department_id):
    digitalfarms = get_object_or_404(DigitalFarms, pk=department_id)
    return render(request, 'farm/digifarms_details.html', {'digitalfarms': digitalfarms, 'active_app': active_app})

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import *


def home_view(request):
    active_app = 'main'
    home_header = ChangeHeaderImages.objects.all()
    social = SocialMediaLinks.objects.all()
    footer = FooterArea.objects.all()
    partners = Partners.objects.all()
    projects = Projects.objects.all()[:5]

    return render(request, 'main/index.html', {'active_app': active_app, "home_header": home_header,
                "social": social, "footer": footer, "partners": partners, "projects": projects})

def contact_view(request):
    contact = ContactPage.objects.all()
    return render(request, 'main/contact.html', {"contact": contact})

def about_view(request):
    abouts = About.objects.all()
    return render(request, 'main/about.html', {'about': abouts})

def news_list(request):
    latest_news = NewsArticle.objects.order_by('-date_published')[:3]
    return render(request, 'news_list.html', {'latest_news': latest_news})

def article_details(request, article_id):
    articles = get_object_or_404(NewsArticle, pk=article_id)
    return render(request, 'article_details', {'articles': articles})

def project_list_view(request):
    projects = Projects.objects.all()
    project_header = ChangeProjectHeaderImage.objects.all()
    return render(request, 'main/project.html', {'projects': projects, 'project_image': project_header})

def project_details_view(request, project_id):
    project_details = get_object_or_404(Projects, pk=project_id)
    return render(request, 'main/project_details', {'project_details': project_details})

def service_view(request):
    services = Services.objects.all()
    # departments = Department.objects.all()[3]
    return render(request, 'main/services.html', {"services": services})

def search_view(request):
    query = request.GET.get('q')
    results = Search.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    return render(request, 'main/search_results.html', {'results': results})

def team_list_view(request):
    members = Team.objects.all()
    return render(request, 'main/team_list.html', {'teams': members})

def team_details_view(request, team_id):
    members = get_object_or_404(Team, team_id=team_id)
    return render(request, 'main/team_details.html', {'team_members': members})

def galleryView(request):
    farms = FarmhiveGallery.objects.all()
    techs = TechhiveGallery.objects.all()
    multimedias = MultimediahiveGallery.objects.all()
    context = {"farms": farms, "techs": techs, "multimedias": multimedias}

    return render(request, 'main/gallery.html', context)

def techhiveView(request):
    techs = TechHive.objects.all()
    return render(request, 'main/tech_hive.html', {'techs': techs})

def multimediaView(request):
    multimedias = MultimediaHive.objects.all()
    return render(request, 'main/multimedia_hive.html', {'multimedias': multimedias})

def farmhiveView(request):
    farms = FarmHive.objects.all()
    return render(request, 'main/farm_hive.html', {'farms': farms})

@login_required
def buy_now(request, item_type, pk):
    item = None
    if item_type == 'tech':
        item = get_object_or_404(TechHive, pk=pk)
    elif item_type == 'multimedia':
        item = get_object_or_404(MultimediaHive, pk=pk)
    elif item_type == 'farm':
        item = get_object_or_404(FarmHive, pk=pk)

    if item:
        request.session['selected_item'] = {'type': item_type, 'pk': pk}
        return redirect('main:details')
    else:
        raise ValueError("No Item selected to proceed with the payment")

techhive/views.py
from django.shortcuts import render


def techHiveHome_view(request):
    return render(request, 'techhive/index.html')

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Meta Tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="themexriver">

    <!-- Page Title -->
    <title> {% block title %}{% endblock %} </title>

    <!-- Favicon and Touch Icons -->
    <link href="{% static 'images/logo/techfarm_logo.jpg' %}" rel="shortcut icon" type="image/png">

    <!-- Icon fonts -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Plugins for this template -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate2.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/slick.css' %}" rel="stylesheet">
    <link href="{% static 'css/slick-theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.transitions.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.fancybox.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap-slider.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-touchspin.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/farm_style.css' %}" rel="stylesheet">
    <link href="{% static 'css/techhive_style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="page-wrapper">
        <div class="preloader">
            <div class="preloader-inner">
                <img src="{% static 'images/preloader.gif' %}" alt>
            </div>
        </div>
        <header id="header" class="site-header header-style-5">
            <div class="topbar topbar-style-2">
                <div class="container">
                    <div class="row">
                        <div class="col col-sm-7">
                            <div class="topbar-contact-info-wrapper">
                                <div class="topbar-contact-info">
                                    <div>
                                        <i class="fa fa-location-arrow"></i>
                                        <div class="details">
                                            <p>5523 Research Park Drive, Suite 110</p>
                                        </div>
                                    </div>
                                    <div>
                                        <i class="fa fa-phone"></i>
                                        <div class="details">
                                            <p>+012 (3546) 547</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col col-sm-5">
                            <div class="social">
                                <span>Follow US: </span>
                                <ul class="social-links">
                                    <li><a href="{{ social.facebook }}"><i class="fa fa-facebook-square"></i></a></li>
                                    <li><a href="{{ social.twitter }}"><i class="fa fa-twitter-square"></i></a></li>
                                    <li><a href="{{ social.lindedIn }}"><i class="fa fa-linkedin-square"></i></a></li>
                                    <li><a href="{{ social.instagram }}"><i class="fa fa-instagram"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="lower-topbar">
                <div class="container">
                    <div class="row">
                        <div class="col col-sm-3">
                            <div class="site-logo">
                                <a href="{% url 'main:home' %}"><img src="{% static 'images/logo/techfarm_logo.jpg' %}" class="site-header-logo" alt></a>
                            </div>
                        </div>

                        <div class="col col-sm-9">
                            <div class="awards">
                                <div>
                                    <div class="icon"></div>
                                    <div class="award-info">
                                        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'main:search' %}">
                                            <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search...">
                                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                                        </form>  
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>

            <nav class="navigation navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="open-btn">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse navigation-holder">
                        <button class="close-navbar"><i class="fa fa-close"></i></button>
                        <ul class="nav navbar-nav">
                            <li class="nav-item"><a href="{% url 'main:home' %}">Home</a></li>
                            <li class="menu-item-has-children nav-item">
                                <a href="#">Departments</a>
                                <ul class="sub-menu">
                                    <li><a href="{% url 'main:farmhive' %}">Farm Hive</a></li>
                                    <li><a href="{% url 'main:multihive' %}">Multimedia Hive</a></li>
                                    <li><a href="{% url 'main:techhive' %}">Tech Hive</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a href="{% url 'main:services' %}">Services</a></li>
                            <li class="nav-item"><a href="{% url 'main:project_list' %}">Projects</a></li>
                            <li class="nav-item"><a href="{% url 'main:team' %}">Team</a></li>
                            <li class="nav-item"><a href="{% url 'main:gallery' %}">Gallery</a></li>
                            <li class="nav-item"><a href="{% url 'main:about' %}">About</a></li>
                            <li class="nav-item"><a href="{% url 'main:contact' %}">Contact</a></li>
                        </ul>
                    </div>

                    <div class="create-account">
                        {% if user_logged_in %}
                        <div class="mini-account">
                            <button class="menu-item-has-children cart-toggle-btn nav-item"><i class="fa fa-user" aria-hidden="true"></i>Account</button>
                            <div class="top-cart-content">
                                <div class="top-cart-items">
                                    <div class="top-cart-item clearfix">
                                        <div class="">
                                            <a href="{% url 'account:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
                                        </div>
                                    </div>
                                    <div class="top-cart-item clearfix">
                                        <div class="">
                                            <a href="{% url 'cart:view' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="mini-account">
                            <button class="menu-item-has-children cart-toggle-btn nav-item"><i class="fa fa-user" aria-hidden="true"></i>Account</button>
                        
                            <div class="top-cart-content">
                                <div class="top-cart-items">
                                    <div class="top-cart-item clearfix">
                                        <div class="">
                                            <a href="{% url 'account:login' %}"><i class="fa fa-user-plus" aria-hidden="true"></i> Login</a>
                                        </div>
                                    </div>
                                    <div class="top-cart-item clearfix">
                                        <div class="">
                                            <a href="{% url 'account:signup' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Signup</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </nav>
        </header>

        <div>
            {% block content %} 

            {% endblock %}
        </div>

        <!-- start site-footer -->
        <footer class="site-footer">
            <div class="upper-footer">
                <div class="container">
                    <div class="row">
                        <div class="col col-md-3 col-sm-6">
                            <div class="widget about-widget">
                                <div class="footer-logo"><img src="{% static 'images/logo/techfarm_logo.jpg' %}" class="site-header-logo" alt></div>
                                <ul class="contact-info">
                                    <li><i class="fa fa-home"></i> </li>
                                    <li><i class="fa fa-phone"></i></li>
                                    <li><i class="fa fa-home"></i> Working Hours: <br>Mon-Fri (9 am - 8 pm)</li>
                                </ul>
                            </div>
                        </div>

                        <div class="col col-md-3 col-sm-6">
                            <div class="widget service-links-widget">
                                <h3>Departments</h3>
                                <ul>
                                    <li><a href="{% url 'farm:home' %}">Agriculture</a></li>
                                    <li><a href="#">Multimedia</a></li>
                                    <li><a href="#">Technology</a></li>
                                </ul>
                            </div>
                        </div>

                        <div class="col col-md-3 col-sm-6">
                            <div class="widget quick-links-widget">
                                <h3>Navigation</h3>
                                <ul>
                                    <li><a href="#">Gallery</a></li>
                                    <li><a href="#">News</a></li>
                                    <li><a href="{% url 'main:contact' %}">Contact Us</a></li>
                                    <li><a href="{% url 'main:about' %}">About</a></li>
                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="copyright-info">
                <div class="container">
                    <p><a target="_blank" href="{% url 'main:home' %}">Techfarm</a></p>
                </div>
            </div>
        </footer>

    </div>
    <!-- end of page-wrapper -->

    <!-- All JavaScript files
    ================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Plugins for this template -->
    <script src="{% static 'js/jquery-plugin-collection.js' %}"></script>
    <script src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>

    <!-- Custom script for this template -->
    <script src="{% static 'js/script.js' %}"></script>

    <!-- Hech Hive js-->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'plugins/scroll-fixed\jquery-scrolltofixed-min.js' %}"></script>
    <script src="{% static 'js/tech_script.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
</body>

</html>

main/templates/main/details.html
{% extends 'main/base.html' %}
{% block title %}Details {% endblock %}
{% block content %}
{% load static %}

{% if request.session.selected_item %}
    <p>You have selected an item:</p>
    <p>Type: {{ request.session.selected_item.type }}</p>
    <p>PK: {{ request.session.selected_item.pk }}</p>
    <!-- Display more details about the selected item -->
{% else %}
    <p>No item selected.</p>
{% endif %}

{% endblock %}

main/templates/main/gallery.html
{% extends 'main/base.html' %}
{% block title %}Gallery{% endblock %}
{% block content %}
{% load static %}


<div class="breadcrumb-area">
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center" style="background-image: url('/static/images/body-bg.jpg');">
        <h2 class="headers">ABOUT US</h2>
        <h3 class="header-content"></h3>
    </div>
</div>

<div class="container">
    <h1 class="mt-5 mb-4">Related Video</h1>
    <div class="row">
        {% for video in videos %}
        <div class="col-md-4">
            <div class="video-card">
                <h2 class="video-title">{{ video.title }}</h2>
                <video class="video-file" controls>
                    <source src="{{ video.video.url }}" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                <p class="text-muted mt-3">Uploaded on {{ video.created_at }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container mt-5">
    <h1 class="text-center mb-4">Related Pictures</h1>
    <div class="row">
        {% for picture in pictures %}
        <div class="col-md-4">
            <div class="card picture-card">
                <img src="{{ picture.image.url }}" class="card-img-top" alt="{{ picture.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ picture.title }}</h5>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/main/news_list.html
{% extends 'main/base.html' %}
{% block title %}Details {% endblock %}
{% block content %}
{% load static %}

<div class="breadcrumb-area">
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center" style="background-image: url('/static/images/body-bg.jpg');">
        <h2 class="headers">Trending</h2>
        <h3 class="header-content"></h3>
    </div>
</div>

{% endblock %}

main/templates/main/project.html
{% extends 'main/base.html' %}
{% block title %}Projects{% endblock %}
{% block content %}
{% load static %}

<div class="breadcrumb-area">
    <div class="top-breadcrumb-area bg-img bg-overlay d-flex align-items-center justify-content-center" style="background-image: url('{{ project_header.image.url }}');">
        <h2 class="headers">Projects</h2>
        <h3 class="header-content">{{ project_header.short_content }}</h3>
    </div>
</div>

<div class="container">
    <div class="cl-project">
        <div class="row">
            <div class="col-lg-4">
                {% for project in projects %}
                    <h3>{{ project.name }}</h3>
                    <video src="{{ project.videofile.url }}"></video>
                    <h4>{{ project.description }}</h4>
                    <h4>{{ project.country }}</h4>
                    <p>{{ project.content }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/team_list.html
{% extends 'main/base.html' %}
{% block title %}Team{% endblock %}
{% block content %}
{% load static %}

<div class="our-team team-11">
    <div class="container">
        <div class="session-title row">
              <h2>Take a look at Our Team</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce fringilla vel nisl a dictum. Donec ut est arcu. Donec hendrerit velit</p>
        </div>
        <div class="row team-row">
            <div class="col-md-3 col-sm-6">
                    <div class="single-usr">
                        {% for member in members %}
                            <img src="{{ member.image.url }}" alt="">
                            <div class="det-o">
                                <h3>{{ member.title }}. {{ member.name_of_team_member }}</h3>
                                <h4>{{ member.position }}</h4>
                                <p>
                                    {% if member.bio|length > 100 %}
                                        {{ member.bio|slice:"100"}}....
                                        <a href="{% url 'main:team_details' team_member.team_id %}">Read More"</a>
                                    {% else %}
                                        {{ member.bio }}
                                    {% endif %}
                                </p>
                                <p>{{ member.date_joined }}</p>
                            </div>
                        {% endfor %}
                    </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-usr">
                    <img src="{% static 'images/main/team-memb2.jpg' %}" alt="">
                    <div class="det-o">
                        <h4>David Kanuel</h4>
                        <i>Business Analsist</i>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-usr">
                    <img src="{% static 'images/main/team-memb3.jpg' %}" alt="">
                    <div class="det-o">
                        <h4>David Kanuel</h4>
                        <i>Project Manager</i>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="single-usr">
                    <img src="{% static 'images/main/team-memb4.jpg' %}" alt="">
                    <div class="det-o">
                        <h4>David Kanuel</h4>
                        <i>Team Leader</i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}